font_family firacode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
# cursor #f2cdcd
dynamic_background_opacity yes

map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard
map ctrl+shift+c send_text normal \x03
confirm_os_window_close 0


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME 
shell /run/current-system/sw/bin/zsh
