color0 #1d100f
color1 #ffb4ab
color2 #ffb3ae
color3 #ffb3ae
color4 #ffb871
color5 #ffb3ae
color6 #ffb3ae
color7 #f7dcda
color8 #a98987
color9 #ffb4ab
color10 #ffb3ae
color11 #ffb3ae
color12 #ffb871
color13 #ffb3ae
color14 #ffb3ae
color15 #f7dcda

cursor                #f7dcda
cursor_text_color     #1d100f
background            #1d100f
foreground            #f7dcda
selection_foreground  #e2bebc
selection_background  #5a413f
active_border_color   #ffb3ae
inactive_border_color #5a413f
url_color             #ffb3ae

active_tab_foreground   #68000c
active_tab_background   #ffb3ae
inactive_tab_foreground #e2bebc
inactive_tab_background #5a413f
cursor_trail_color      #e2bebc
