#!/usr/bin/env bash
export LD_LIBRARY_PATH=/run/current-system/sw/lib:$LD_LIBRARY_PATH

TLO_BIN="/etc/nixos/tlo-layer"
COLOR="000000"
OFFSET_Y=-32
DP1_Y_MAX=1080
HDMI_Y_OFFSET=1080

read -r X Y W H <<< $(slurp -f "%x %y %w %h")
[ -z "$X" ] && exit 1

CORRECTED_Y=$((Y + OFFSET_Y))

if [ "$Y" -lt "$DP1_Y_MAX" ]; then
    "$TLO_BIN" "$X" "$CORRECTED_Y" "$W" "$H" "DP-1" "$COLOR" &
else
    LOCAL_Y=$((Y - HDMI_Y_OFFSET + OFFSET_Y))
    "$TLO_BIN" "$X" "$LOCAL_Y" "$W" "$H" "HDMI-A-2" "$COLOR" &
fi
